const fetchError = async () => {
  throw new Error('Something went wrong');
};
module.exports = fetchError;
